const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.ScriptsInEvents.EventSheet1_Event83_Act2,
		C3.ScriptsInEvents.EventSheet1_Event84_Act2,
		C3.Plugins.Button.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{Function: 0},
	{Keyboard: 0},
	{Score: 0},
	{Touch: 0},
	{Highscore: 0},
	{Score_txt: 0},
	{Log: 0},
	{LocalStorage: 0},
	{Flash: 0},
	{Play_btn: 0},
	{Mouse: 0},
	{Menu_btn: 0},
	{Title_text: 0},
	{How_text: 0},
	{Timer: 0},
	{ScrollTo: 0},
	{Background: 0},
	{Lives: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Bullet_Player: 0},
	{shoot: 0},
	{Rotate: 0},
	{Sine: 0},
	{Enemies: 0},
	{Bullet_Enemy: 0},
	{Stars: 0},
	{Particles_Player: 0},
	{Particles_Enemy_2: 0},
	{Particles_Enemy: 0},
	{Powerup: 0},
	{Audio: 0},
	{Button: 0},
	{Browser: 0},
	{Button2: 0},
	{Button3: 0},
	{Button4: 0},
	{Hiscore: 0},
	{Next: 0},
	{Howtoplay: 0},
	{shoot_rate: 0},
	{powerup: 0},
	{enemy_speed: 0},
	{bg_speed: 0}
];

self.InstanceType = {
	Function: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Highscore: class extends self.ITextInstance {},
	Score_txt: class extends self.ITextInstance {},
	Log: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Play_btn: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Menu_btn: class extends self.ITextInstance {},
	Title_text: class extends self.ITextInstance {},
	How_text: class extends self.ITextInstance {},
	Background: class extends self.ISpriteInstance {},
	Lives: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Bullet_Player: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Bullet_Enemy: class extends self.ISpriteInstance {},
	Stars: class extends self.ITiledBackgroundInstance {},
	Particles_Player: class extends self.IParticlesInstance {},
	Particles_Enemy_2: class extends self.IParticlesInstance {},
	Particles_Enemy: class extends self.IParticlesInstance {},
	Powerup: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Button2: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Button4: class extends self.IButtonInstance {}
}